const express = require('express')
const router = express.Router()
const passport = require('passport')
const { authenticated, isUser, isSeller } = require('../middleware/auth')
const userController = require('../controllers/user-controller')
const cartController = require('../controllers/cart-controller')
const productController = require('../controllers/product-controller')
const categoryController = require('../controllers/category-controller')
const shopController = require('../controllers/shop-controller')
const orderController = require('../controllers/order-controller')
const upload = require('../middleware/multer')
const { errorHandler } = require('../middleware/error-handler')

router.get('/api/v1/products', productController.getProducts)
router.get('/api/v1/categories', categoryController.getCategories)
router.post('/api/v1/signup', userController.signUp)
router.post('/api/v1/signin', passport.authenticate('local', { session: false }), userController.signIn)
router.get('/api/v1/user', authenticated, userController.getUser)
router.post('/api/v1/order', authenticated, isUser, orderController.addOrder)
router.post('/api/v1/cart/:productId', authenticated, isUser, cartController.addCartItem)
router.delete('/api/v1/cart/:cartItemId', authenticated, isUser, cartController.removeCartItem)
router.put('/api/v1/cart/:cartItemId', authenticated, isUser, cartController.toggleCartItem)
router.get('/api/v1/cart', authenticated, isUser, cartController.getCartItems)
router.get('/api/v1/shop', authenticated, isSeller, shopController.getProducts)
router.post('/api/v1/shop', authenticated, isSeller, upload.single('image'), shopController.addProduct)
router.put('/api/v1/shop', authenticated, isSeller, shopController.toggleProduct)
router.use('/', errorHandler)

module.exports = router
